# Generated by Django 3.2 on 2021-05-20 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counter_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.FloatField(default=0),
        ),
    ]
